const express=require("express")
const {addAd,deleteAd,getAds,getLatestAds,getOldestAds,highestPriceFirst,lowestPriceFirst,getallads,getsinglead,getBasedOnType,fetchBasedOnGivenPrice,petFriendly,notPetFriendly}=require("../controllers/RealEstateAd.js")
const VerifyToken=require("../VerifyToken.js")
const router=express.Router()
router.post("/add_ad",VerifyToken,addAd)
router.delete("/deleteAd/:id",VerifyToken,deleteAd)
router.get("/getads/:page",getAds)
router.get("/getlatestads",getLatestAds)
router.get("/petfriendly/:location",petFriendly)
router.get("/notpetfriendly/:location",notPetFriendly)
router.get("/getoldestads",getOldestAds)
router.get("/getallads/:location",getallads)
router.get("/getsinglead/:id",getsinglead)
router.get("/highestpricefirst",highestPriceFirst)
router.get("/lowestpricefirst",lowestPriceFirst)
router.get("/getbasedontype/:type/:location",getBasedOnType)
router.get("/getbasedonpricegiven/:first/:second/:location",fetchBasedOnGivenPrice)
module.exports = router;
