const mongoose=require("mongoose")
const carAdSchema=new mongoose.Schema(
    {
        userId:
        {
            type:String,
            required:true
        }
        ,title:
        {
            type:String,
            required:true,
        },
        description:
        {
            type:String,
        },
        Img:
        {
            type:[String]
            ,default:[""]
        },
        condition:
        { 
             type:String
        },
        make:
        { 
            type:String
        },
        kilometers:
        {
            type:Number,
            default:0
        },
        price:
        {
            type:Number
        },
        year:
        {
            type:Number
        },
        color:
        {
            type:String
        },
        transmission:
        {
            type:String
        },
        fuelType:
        {
            type:String
        },
        location:
        {
            type:String
        },
        adType:
        {
            type:String,
            default:"auto"
        },
        rental:{
type:Boolean,
default:false
        },
        vidwedAds:
        {
            type:[String],
            default:[]
        },
       
        resetToken:String,
        expireToken:Date
    },{timestamps:true})
    module.exports=mongoose.model("CarAds",carAdSchema)