const mongoose=require("mongoose")
const JobsAdsSchema=new mongoose.Schema(
    {
        userId:
        {
            type:String,
            required:true
        }
        ,title:
        {
            type:String,
            required:true,
        },
        description:
        {
            type:String,
            required:true,
        },
        Img:
        {
            type:[String]
            ,default:[""]
        },location:
        {
            type:String
        },
        type:
        {
type:String  // Ex: fulltime, parttime, remote, hybrid, temporary, contract.
        },
        salary:
        {
            type:Number
        },
        adType:
        {
            type:String,
            default:"job"
        },
        urgent:
        {
            type:String
        }
    },{timestamps:true})
    module.exports=mongoose.model("JobsAds",JobsAdsSchema)