const mongoose=require("mongoose")
const ServicesAdsSchema=new mongoose.Schema(
    {
        userId:
        {
            type:String,
            required:true
        }
        ,title:
        {
            type:String,
            required:true,
        },
        description:
        {
            type:String,
            required:true,
        },
        Img:
        {
            type:[String]
            ,default:[""]
        },
        location:
        {
            type:String
        },
        adType:
        {
            type:String,
            default:"service"
        },
        price:
        {
            type:Number
        }
    },{timestamps:true})
    module.exports=mongoose.model("ServicesAds",ServicesAdsSchema)
