const mongoose=require("mongoose")
const UserSchema=new mongoose.Schema(
    {
        name:
        {
            type:String,
            required:true
        },
        email:
        {
            type:String,
            required:true,
            unique:true
        },
        password:
        {
            type:String
        },
        phone:
        {
            type:Number
        },
        vidwedAds:
        {
            type:[String],
            default:[]
        },
        Img:{type:String,default:""},
        resetToken:String,
        expireToken:Date
    },{timestamps:true})
    module.exports=mongoose.model("Users",UserSchema)